Alfresco/alfresco-ios-app

AlfrescoApp.xcodeproj/project.pbxproj
AlfrescoDocumentPicker/DocumentPickerViewController.m
AlfrescoDocumentPicker/Info.plist
AlfrescoDocumentPicker/Model/FileMetadata.h
AlfrescoDocumentPicker/Model/FileMetadata.m
AlfrescoDocumentPicker/Model/PersistentQueueStore.h
AlfrescoDocumentPicker/Model/PersistentQueueStore.m
AlfrescoDocumentPicker/Utilities/Utilities.h
AlfrescoDocumentPicker/Utilities/Utilities.m
AlfrescoDocumentPickerFileProvider/AlfrescoDocumentPickerFileProvider-Prefix.pch
AlfrescoDocumentPickerFileProvider/AlfrescoDocumentPickerFileProvider.entitlements
AlfrescoDocumentPickerFileProvider/FileProvider.m

Open mode working as shown in the sprint demo. Only change is that the filename now displayed in MS Word.

MOBILE-3179

---

AlfrescoApp.xcodeproj/xcshareddata/xcschemes/AlfrescoApp.xcscheme
AlfrescoApp/Supporting Files/Settings.bundle/Root.plist

Xcode 6.2 project file updates.

Update visible version number in Settings to 2.1 for Xcode builds.

---

AlfrescoApp.xcodeproj/project.pbxproj
AlfrescoApp/Supporting Files/AlfrescoApp-Prefix.pch
AlfrescoApp/Utils/Categories/UILabel+Insets.m
AlfrescoApp/Utils/Categories/UITextField+RightAlignmentSpacingFix.h
AlfrescoApp/Utils/Categories/UITextField+RightAlignmentSpacingFix.m
AlfrescoApp/Utils/Categories/UIViewController+Swizzled.m

Also wrapped all method swizzling in ```dispatch_once``` blocks

MOBILE-2912

---

AlfrescoApp/Model/Managers/SyncManager.m

This is the fix for Mobile-3254

Fix for preview functionality of files that are not synced

---

AlfrescoApp/View Controllers/Connection Diagnostic View Controller/ConnectionDiagnosticViewController.m

Added Alfresco in front of the enum name.

Fix for enum naming problem

---

AlfrescoApp.xcodeproj/xcshareddata/xcschemes/AlfrescoApp.xcscheme

Update pre-build script to ensure App Store binary has version number stamped correctly

Build script update

---

AlfrescoApp Tests/AlfrescoApp Tests-Info.plist
AlfrescoApp.xcodeproj/project.pbxproj
AlfrescoApp.xcodeproj/xcshareddata/xcschemes/AlfrescoApp.xcscheme
AlfrescoApp/Supporting Files/Settings.bundle/Root.plist
AlfrescoDocumentPicker/Info.plist
AlfrescoDocumentPickerFileProvider/Info.plist
tools/set_build_number.sh

Update all target version numbers to match that of parent AlfrescoApp… (resolve iTunes Connect warning)
- Also updated set_build_number.sh and pre-build step to use agvtool to simplify versioning all targets

Versioning updates

---

AlfrescoApp.xcodeproj/project.pbxproj
AlfrescoApp/View Controllers/FileFolder View Controller/BaseCollectionViewFlowLayout.m
AlfrescoApp/View Controllers/FileFolder View Controller/BaseFileFolderCollectionViewController.h
AlfrescoApp/View Controllers/FileFolder View Controller/BaseLayoutAttributes.h
AlfrescoApp/View Controllers/FileFolder View Controller/BaseLayoutAttributes.m
AlfrescoApp/View Controllers/FileFolder View Controller/Cell/FileFolderCollectionViewCell.m
AlfrescoApp/View Controllers/FileFolder View Controller/Cell/LoadingCollectionViewCell.h
AlfrescoApp/View Controllers/FileFolder View Controller/Cell/LoadingCollectionViewCell.m
AlfrescoApp/View Controllers/FileFolder View Controller/FileFolderCollectionViewController.m
AlfrescoApp/View Controllers/FileFolder View Controller/FileFolderCollectionViewController.storyboard
AlfrescoApp/View Controllers/ParentCollectionViewController.m

Changed the loading shown at the bottom of the list view from being a section footer to a simple collection view cell. Also fixed some other small problems encountered.

Fixed UI problems relating to IOS-53

---

AlfrescoApp/View Controllers/FileFolder View Controller/BaseCollectionViewFlowLayout.m
AlfrescoApp/View Controllers/FileFolder View Controller/Cell/FileFolderCollectionViewCell.h
AlfrescoApp/View Controllers/FileFolder View Controller/Cell/FileFolderCollectionViewCell.m
AlfrescoApp/View Controllers/FileFolder View Controller/FileFolderCollectionViewController.m
AlfrescoApp/View Controllers/FileFolder View Controller/FileFolderCollectionViewController.storyboard

Fixed several bugs:
- IOS-117
- IOS-122
- IOS-125

Bug fixes for UICollectionView refactor

---

AlfrescoApp/View Controllers/FileFolder View Controller/BaseCollectionViewFlowLayout.h
AlfrescoApp/View Controllers/FileFolder View Controller/BaseCollectionViewFlowLayout.m
AlfrescoApp/View Controllers/FileFolder View Controller/BaseLayoutAttributes.h
AlfrescoApp/View Controllers/FileFolder View Controller/Cell/FileFolderCollectionViewCell.m
AlfrescoApp/View Controllers/FileFolder View Controller/FileFolderCollectionViewController.m
AlfrescoApp/View Controllers/FileFolder View Controller/FileFolderCollectionViewController.storyboard
AlfrescoApp/Views/Thumbnail Image View/ThumbnailImageView.h
AlfrescoApp/Views/Thumbnail Image View/ThumbnailImageView.m

Work for IOS-26 (Sprint 3 work)

---

AlfrescoApp/Constants/Constants.h
AlfrescoApp/Constants/Constants.m
AlfrescoApp/Supporting Files/en.lproj/Localizable.strings
AlfrescoApp/View Controllers/Accounts View Controllers/New Account/AccountInfoViewController.m
AlfrescoApp/View Controllers/Main Menu View Controller/Model/MainMenuConfigurationBuilder.m
AlfrescoApp/View Controllers/Profile Selection View Controller/ProfileSelectionViewController.m

- Banner added after a profile is changed
- Profile descriptions
- Other internal constant updates to support future development

Changes following suggestions during sprint demo

---

AlfrescoApp/View Controllers/FileFolder View Controller/BaseCollectionViewFlowLayout.m
AlfrescoApp/View Controllers/FileFolder View Controller/BaseFileFolderCollectionViewController.h
AlfrescoApp/View Controllers/FileFolder View Controller/BaseLayoutAttributes.h
AlfrescoApp/View Controllers/FileFolder View Controller/Cell/FileFolderCollectionViewCell.m
AlfrescoApp/View Controllers/FileFolder View Controller/FileFolderCollectionViewController.h
AlfrescoApp/View Controllers/FileFolder View Controller/FileFolderCollectionViewController.m
AlfrescoApp/View Controllers/FileFolder View Controller/FileFolderCollectionViewController.storyboard

Work for IOS-57 (part of IOS-26 story)

Grid View Layout

---

AlfrescoApp/View Controllers/FileFolder View Controller/BaseCollectionViewFlowLayout.m
AlfrescoApp/View Controllers/FileFolder View Controller/BaseLayoutAttributes.m
AlfrescoApp/View Controllers/FileFolder View Controller/Cell/FileFolderCollectionViewCell.m
AlfrescoApp/View Controllers/FileFolder View Controller/FileFolderCollectionViewController.m

Known problem: 
* go to File Folder in list layout
* swipe to delete an item
* add a new folder (of file) that will be inserted on top of the cell that has "Delete" button shown
Expected result: delete button should be displayed at the correct index after the insert operation completes
Result: delete button changes is displayed at the wrong index
An issue should be opened for this item.

Fix for IOS-210 and IOS-216

---

AlfrescoApp/View Controllers/FileFolder View Controller/BaseCollectionViewFlowLayout.m
AlfrescoApp/View Controllers/FileFolder View Controller/BaseLayoutAttributes.h
AlfrescoApp/View Controllers/FileFolder View Controller/BaseLayoutAttributes.m
AlfrescoApp/View Controllers/FileFolder View Controller/Cell/FileFolderCollectionViewCell.m
AlfrescoApp/View Controllers/FileFolder View Controller/Cell/FileFolderCollectionViewCell.xib

Work for IOS-321, IOS-315

---

AlfrescoApp/View Controllers/FileFolder View Controller/BaseCollectionViewFlowLayout.m
AlfrescoApp/View Controllers/FileFolder View Controller/BaseLayoutAttributes.h
AlfrescoApp/View Controllers/FileFolder View Controller/BaseLayoutAttributes.m
AlfrescoApp/View Controllers/FileFolder View Controller/Cell/FileFolderCollectionViewCell.m
AlfrescoApp/View Controllers/FileFolder View Controller/Cell/FileFolderCollectionViewCell.xib

This one includes multiple fixes for auto layout problems in switching from grid to list view.

Fix for IOS-322

---

AlfrescoApp/View Controllers/FileFolder View Controller/BaseCollectionViewFlowLayout.m

- Also reported via #591 on GitHub

IOS-363: Application crash when delete button is revealed

---

AlfrescoApp.xcodeproj/project.pbxproj
AlfrescoApp/Constants/Constants.h
AlfrescoApp/View Controllers/Main Menu View Controller/Model/MainMenuConfigurationBuilder.m
AlfrescoApp/View Controllers/Search View Controller/SearchViewController.h
AlfrescoApp/View Controllers/Search View Controller/SearchViewController.m
AlfrescoApp/View Controllers/Sites View Controller/SitesListViewController.h
AlfrescoApp/View Controllers/Sites View Controller/SitesListViewController.m
AlfrescoApp/View Controllers/Sites View Controller/SitesTableListViewController.h
AlfrescoApp/View Controllers/Sites View Controller/SitesTableListViewController.m
AlfrescoApp/View Controllers/Sites View Controller/SitesViewController.h
AlfrescoApp/View Controllers/Sites View Controller/SitesViewController.m

Site Finder Refactor 

---

AlfrescoApp.xcodeproj/project.pbxproj
AlfrescoApp/Supporting Files/en.lproj/Localizable.strings
AlfrescoApp/View Controllers/Accounts View Controllers/AccountsViewController.xib
AlfrescoApp/View Controllers/Accounts View Controllers/New Account/AccountInfoDetailsViewController.h
AlfrescoApp/View Controllers/Accounts View Controllers/New Account/AccountInfoDetailsViewController.m
AlfrescoApp/View Controllers/Accounts View Controllers/New Account/AccountInfoDetailsViewController.xib
AlfrescoApp/View Controllers/Accounts View Controllers/New Account/AccountInfoViewController.m
AlfrescoApp/View Controllers/Accounts View Controllers/New Account/AccountInfoViewController.xib
AlfrescoApp/View Controllers/Accounts View Controllers/New Account/AccountTypeSelectionViewController.m
AlfrescoApp/View Controllers/Accounts View Controllers/New Account/AccountTypeSelectionViewController.xib
AlfrescoApp/View Controllers/Accounts View Controllers/New Account/NewAccountViewController.h
AlfrescoApp/View Controllers/Accounts View Controllers/New Account/NewAccountViewController.m
AlfrescoApp/View Controllers/Accounts View Controllers/New Account/NewAccountViewController.xib
AlfrescoApp/View Controllers/Activities View Controller/ActivitiesViewController.xib
AlfrescoApp/View Controllers/ParentCollectionViewController.xib
AlfrescoApp/View Controllers/Search View Controller/SearchResultsTableViewController.xib
AlfrescoApp/View Controllers/Search View Controller/SearchViewController.xib
AlfrescoApp/View Controllers/Site Members View Controller/SiteMembersViewController.xib

There are several commits relating to IOS-358 implementation.

Work for IOS-358 and a warning fix

---

AlfrescoApp/View Controllers/Main Menu View Controller/MainMenuConfigurationViewController.m
AlfrescoApp/View Controllers/Main Menu View Controller/MainMenuViewController.m
AlfrescoApp/View Controllers/Switcher View Controller/SwitchViewController.m

Also reloads the account menu item to ensure the avatar is cleared.

IOS-570: Settings panel appears recursively when user has no accounts

---

AlfrescoApp/Model/Managers/RealmSyncManager.m

Added handling for other account configuration related events

IOS-522: Disable sync via server side config

---

AlfrescoApp/Model/Managers/AlfrescoProtectionAwareFileManager.m
AlfrescoApp/Model/Managers/SecurityManager.m
AlfrescoApp/Supporting Files/App Property Lists/UserPreferences.plist
AlfrescoApp/Supporting Files/de.lproj/Localizable.strings
AlfrescoApp/Supporting Files/en.lproj/Localizable.strings
AlfrescoApp/Supporting Files/es.lproj/Localizable.strings
AlfrescoApp/Supporting Files/fr.lproj/Localizable.strings
AlfrescoApp/Supporting Files/it.lproj/Localizable.strings
AlfrescoApp/Supporting Files/ja.lproj/Localizable.strings
AlfrescoApp/Supporting Files/zh-Hans.lproj/Localizable.strings
AlfrescoApp/View Controllers/Accounts View Controllers/AccountsViewController.m
AlfrescoApp/View Controllers/PinViewController/PinViewController.h
AlfrescoApp/View Controllers/PinViewController/PinViewController.m
AlfrescoApp/View Controllers/Settings View Controller/SettingsViewController.m

IOS-628: : Passcode is only available for paying on premise and cloud customers
IOS-638: Add Passcode phrase to File Protection disabled message

IOS-628 & IOS-638

---

AlfrescoApp/Model/Managers/RealmSyncManager.m

Added a fix for the 2nd scenario.

IOS-789: Loss of content when disable sync via Server-side Config

---

AlfrescoApp/Supporting Files/en.lproj/InfoPlist.strings
AlfrescoApp/Supporting Files/en.lproj/Localizable.strings
AlfrescoDocumentPicker/en.lproj/Localizable.strings

Rebranding

---

AlfrescoApp.xcodeproj/project.pbxproj
AlfrescoApp/Model/Services/SearchIndexService.h
AlfrescoApp/Model/Services/SearchIndexService.m

Added placeholder class and methods for handling search results

---

AlfrescoDocumentPickerFileProvider/FileProvider.m

- IOS-1158 - Not able to save a file in online mode after I have tried to save it in offline mode
- IOS-1159 - Not able to save same file in separate synced folders
- IOS-1160 - File not saved on chid folder of a synced folder

Fix for issues: IOS-1158, IOS-1159, IOS-1160

---

AlfrescoApp/Utils/UniversalDevice.m
AlfrescoApp/Views/Action Collection View/ActionCollectionView.m

[ACS] The application is crashing when going online while being on info of a synced folder

IOS-1243: 

---

AlfrescoApp/Model/Managers/RealmSyncManager.m

Also did some small cleaning by removing some commented code.

Merged master into 2.7.1-dev branch 

---

AlfrescoApp/Utils/UniversalDevice.m
AlfrescoApp/View Controllers/Switcher View Controller/SwitchViewController.m

MOBILEAPPS-259 [ACS] The Upload to folder is not working

---

AlfrescoApp/Supporting Files/de.lproj/Localizable.strings
AlfrescoApp/Supporting Files/en.lproj/Localizable.strings
AlfrescoApp/Supporting Files/es.lproj/Localizable.strings
AlfrescoApp/Supporting Files/fr.lproj/Localizable.strings
AlfrescoApp/Supporting Files/it.lproj/Localizable.strings
AlfrescoApp/Supporting Files/ja.lproj/Localizable.strings
AlfrescoApp/Supporting Files/zh-Hans.lproj/Localizable.strings

Updated localised files for iOS ACS 2.8 for all languages based on EN 2020-05-04, as per ticket MOBILEAPPS-231.

Updated localised files for iOS ACS 2.8 for all languages based on EN 2020-05-04, as per ticket MOBILEAPPS-231.

---

AlfrescoApp.xcodeproj/project.pbxproj
AlfrescoApp/Model/Managers/AIMSLoginService.swift
AlfrescoApp/View Controllers/Take Continous Photos View Controller/CameraController.swift
Podfile
Podfile.lock

Fixed crash with certain ultra-wide cameras when taking multiple photos

---

AlfrescoApp.xcodeproj/project.pbxproj
AlfrescoApp/Model/Managers/AIMSLoginService.swift
Podfile
Podfile.lock

- Fixed breaking changes in login service

Updated AlfrescoAuth dependency to latest publicly available version

---

AlfrescoApp.xcodeproj/project.pbxproj
AlfrescoApp/Supporting Files/en.lproj/Localizable.strings
Podfile.lock

Reverts Alfresco/alfresco-ios-app#1187

Revert "App crash real m"

---

AlfrescoApp/Model/Managers/AnalyticsManager.m
Podfile.lock

Fixed crash on iOS 15+
